manifest:
  version: 0.8

  self:
    path: dev

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.0.0
      import:
        file: west.yml
        path-prefix: deps
        name-allowlist:
          - nrf
          - zephyr
          - hal_nordic
          - tinycrypt
          - segger
          - cmsis